# Generated by Django 2.2.1 on 2019-11-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '分类(视频分类)',
                'db_table': 'Classification',
            },
        ),
        migrations.CreateModel(
            name='ImgVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.FileField(max_length=32, upload_to='./img/img_video/', verbose_name='图片路径')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=128, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '图片视频',
                'db_table': 'ImgVideo',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '难度',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态')),
                ('weight', models.CharField(max_length=32, verbose_name='权重(按从大到小)')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=32, verbose_name='简介')),
                ('img', models.ImageField(upload_to='./img/video/', verbose_name='图片')),
                ('href', models.CharField(max_length=256, verbose_name='链接')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=False, to='myadmin.Classification')),
                ('level', models.ForeignKey(on_delete=False, to='myadmin.Level')),
            ],
            options={
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('classification', models.ManyToManyField(to='myadmin.Classification')),
            ],
            options={
                'verbose_name_plural': '方向(视频方向)',
                'db_table': 'Direction',
            },
        ),
    ]
