# Generated by Django 2.2.1 on 2019-10-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name_plural': '分类(视频分类)'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': '视频'},
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, '下线'), (2, '上线')], default=1, verbose_name='状态'),
        ),
    ]
