# Generated by Django 2.1.5 on 2019-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20191029_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='myadmin.Direction'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='classification',
            field=models.ManyToManyField(null=True, to='myadmin.Classification'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态'),
        ),
    ]
